export enum ErrorStatus {
  // 400s: Client Errors
  RESSOURCE_NOT_FOUND = 'RESSOURCE_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_LANGUAGE = 'INVALID_LANGUAGE',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // 401s: Authentication Errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  BAD_CREDENTIALS = 'BAD_CREDENTIALS',
  OAUTH_AUTHENTICATION_FAILED = 'OAUTH_AUTHENTICATION_FAILED',
  JWT_TOKEN_EXPIRED = 'JWT_TOKEN_EXPIRED',

  // 403s: Authorization Errors
  FORBIDDEN = 'FORBIDDEN',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',

  // 409s: Conflict Errors
  CONFLICT = 'CONFLICT',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // 500s: Server Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}
