export enum SseEventType {
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  MOVIE_WATCHLIST_IDS_UPDATE = 'MOVIE_WATCHLIST_IDS_UPDATE',
  MOVIE_FAVORITE_IDS_UPDATE = 'MOVIE_FAVORITE_IDS_UPDATE',
  MOVIE_TOTAL_RUNTIME_UPDATE = 'MOVIE_TOTAL_RUNTIME_UPDATE',
  SERIE_WATCHLIST_IDS_UPDATE = 'SERIE_WATCHLIST_IDS_UPDATE',
  SERIE_FAVORITE_IDS_UPDATE = 'SERIE_FAVORITE_IDS_UPDATE',
  SERIE_SEASON_WATCHLIST_IDS_UPDATE = 'SERIE_SEASON_WATCHLIST_IDS_UPDATE',
  SERIE_EPISODE_WATCHLIST_IDS_UPDATE = 'SERIE_EPISODE_WATCHLIST_IDS_UPDATE',
  SERIE_TOTAL_RUNTIME_UPDATE = 'SERIE_TOTAL_RUNTIME_UPDATE'
}
