export enum Emotion {
  MOVED = 'MOVED',
  HAPPY = 'HAPPY',
  SAD = 'SAD',
  INSPIRED = 'INSPIRED',
  THRILLED = 'THRILLED',
  SCARED = 'SCARED',
  BORED = 'BORED',
  DISAPPOINTED = 'DISAPPOINTED',
  CONFUSED = 'CONFUSED',
  RELAXED = 'RELAXED'
}
