name: Build, Push and Deploy Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: NODE_OPTIONS="--max-old-space-size=4096"
          tags: |
            ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e  # Exit the script if any command fails

            echo "🔄 Connecting to the server..."
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "📥 Pulling the latest Docker image..."
            docker pull ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:latest

            echo "🛑 Stopping and removing the existing container..."
            docker stop quoi-regarder_website || true
            docker rm quoi-regarder_website || true

            echo "🚀 Starting the new container..."
            docker run -d \
              --name quoi-regarder_website \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NUXT_TMDB_API_KEY="${{ secrets.NUXT_TMDB_API_KEY }}" \
              -e NUXT_API_BASE_URL="${{ secrets.NUXT_API_BASE_URL }}" \
              ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:latest

            echo "✅ Deployment completed successfully!"
